language: java
os:
  - osx
env:
  global:
    - AKKA_TEST_TIMEFACTOR=10
    - SBT_TASK_LIMIT=4
script:
  - curl https://raw.githubusercontent.com/paulp/sbt-extras/master/sbt -o sbt ; chmod 755 sbt
  - ./sbt ensimeConfig
  - ./sbt test:compile it:compile
  - ./sbt test it:test
  - rm -rf $HOME/.coursier/cache/v1/https/oss.sonatype.org
cache:
  directories:
  - $HOME/.sbt
  - $HOME/.ivy2
  - $HOME/.m2
  - $HOME/.coursier
notifications:
  email: false
